### ISSUE TITLE
Listen for packets when not doing anything else

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/rfm_edf_ecomanager#10]

**Comment by andygodber** [comment]
Jack – don’t know if you get notified of Wiki updates, but Ive just created some random musings.

**Comment by JackKelly** [comment]
Hi Andy,

No, I don't get email notifications of wiki updates so thanks for pointing me towards your [wiki page](https://github.com/JackKelly/rfm_edf_ecomanager/wiki/Random-observations).  Thanks loads for your observations.

That's great that the code works for all CC transmitters.  Good stuff.

Yes, as you say, some CC transmitters can take 3 CT clamps.  The transmitter is assigned a single ID.  My code should be able to handle the 3 sensors (I currently use 2 CT clamps on a single transmitter and the code seems to handle it)

Regarding range: that'll depend a lot on your aerial setup.  I've been advised that either a half wave whip (without ground plane) or a quarter wave whip with ground plane should work well.  I haven't tinkered much with range / aerials yet.  I'm pretty sure the EcoManager uses and RFM12b so we're on a level playing field there.  And my code uses the same RFM12b configuration parameters the EcoManager uses so we should be on a level playing field there too.  It did occur to me that my code could learn the carrier frequency offsets for each TX and configure the RFM12b to tune to that specific frequency for each TX but that might be a little overkill!

By the way, the best place for a "free form" discussion is probably on the JeeLabs forum: http://forum.jeelabs.net/comment/9316#comment-9316

Thanks again for all your help.
