### ISSUE TITLE
Debug code causes compilation errors

### ISSUE THREAD

**Issue by andygodber** [JackKelly/rfm_edf_ecomanager#12]
Pulled down the latest code after your updates of last night, but the debug code (to display output etc) now causing IDE (1.0.1 W8 64-bit) compilation errors again:

debug.cpp: In function 'void debug(DebugLevel, const char*, ...)':
debug.cpp:14: error: 'millis' was not declared in this scope
debug.cpp:14: error: 'sprintf' was not declared in this scope
debug.cpp:15: error: 'Serial' was not declared in this scope
debug.cpp:24: error: 'va_list' was not declared in this scope
debug.cpp:24: error: expected `;' before 'vl'
debug.cpp:25: error: 'vl' was not declared in this scope
debug.cpp:25: error: 'va_start' was not declared in this scope
debug.cpp:26: error: 'vsprintf' was not declared in this scope
debug.cpp:27: error: 'va_end' was not declared in this scope

**Comment by JackKelly** [comment]
Thanks for the error report.  I think I've fixed it.

**Comment by andygodber** [comment]
Yep - fixed thanks.
Going to raise a different one - not sure CC transmitters being received, EDF ok,
