### ISSUE TITLE
IDE compilation errors

### ISSUE THREAD

**Issue by andygodber** [JackKelly/rfm_edf_ecomanager#2]
Still getting errors (even after Jack's revision) at compile time. IDE 1.0.1 (and 1.0.0) on Windoze 8
Rfm12b.cpp.o: In function `Rfm12b::interrupt_handler()':
C:\Users\Andy\AppData\Local\Temp\build6281000564122575244.tmp/Rfm12b.cpp:78: undefined reference to`spi::select(bool)'
C:\Users\Andy\AppData\Local\Temp\build6281000564122575244.tmp/Rfm12b.cpp:90: undefined reference to `spi::select(bool)'
C:\Users\Andy\AppData\Local\Temp\build6281000564122575244.tmp/Rfm12b.cpp:99: undefined reference to`spi::select(bool)'

**Comment by JackKelly** [comment]
Hi Andy,

Thanks for reporting the error here on github.

I'll install the Arduino IDE on Windows one day soon and try to replicate the bug...

In the mean time, please could you try fiddling with the order of the #includes in the .ino file?  You could also try including including .cpp files in place of the .h files in the .ino file.

**Comment by andygodber** [comment]
Will do - I'll also log a duplicate issue on Robo's code.

**Comment by JackKelly** [comment]
I reproduced the bug on Win7 64-bit and ArduinoIDE 1.0.1 and I've committed a candidate fix.  Let me know if it works for you.

Also, I must emphasise that the code will undergo quite a few changes over the comming days.  At present it's not really ready for anything but casual tinkering.  For example, at the time of writing the IAM IDs are hard-coded, as are the whole-house IDs.

**Comment by andygodber** [comment]
Yep - working here as well (at least earlier versions) -thanks for reviewing.
Earlier version receiving info (eg) IAM 1427111939
1066827 {uid:1263 {t: 1061098, s0: 0, s1: 0, s2: 0}}
1066829 Broken packet received.
1066829 {uid:3386 {t: 1062555, s0: 2791}}
1066833 {uid:3289 {t: 1065439, s0: 0}}
1066926 polling IAM 1427111939
1067027 polling IAM 1427111939
1067128 polling IAM 1427111939
1067229 polling IAM 1427111939

Latest has compile errors in the DEBUG tab, but I can see you're busy working on new releases, so will let code settle before reviewing.

**Comment by JackKelly** [comment]
Great, glad it's working. Thanks for testing it!

Yup, the code is still going through quite big changes at the moment.  I was hoping to have pairing implemented by this evening but that's looking unlikely as I had to fix an unexpected bug earlier today.  Getting there though!

With luck I'll have pairing implemented tomorrow.
