### ISSUE TITLE
Feature: post to Cosm

### ISSUE THREAD

**Issue by andygodber** [JackKelly/rfm_edf_ecomanager#25]
In the pipeline, im sure, but ability to post to COSM would be useful.

**Comment by JackKelly** [comment]
I'm afraid I don't plan to implement any network functionality in this code.  The code is designed to be used with a tethered PC.

If you want to send stuff to Cosm then I'd recommend throwing together a small Python script which runs on a laptop / Raspberry Pi and takes data from the Nanode and pipes it to Cosm, possibly using my [cosmSender](https://github.com/JackKelly/cosmSender) Python script ;)

Yeah, I know, you might be thinking "what's the point of using a Nanode if I don't use the Ethernet port".  For starters I simply don't have time to implement network functionality (it's not entirely trivial on an embedded system), also I'm already starting to run out of code space on the ATMEGA, and finally I ultimately want something which is as reliable as possible, hence adding non-essential features - especially complex ones like TCP/IP - is unlikely to happen I'm afraid, sorry.

**Comment by JackKelly** [comment]
A quick update: cdjackson has forked this code and is planning to implement Ethernet: https://github.com/cdjackson/rfm_edf_ecomanager
